version: '3.8'

networks:
  mysql-network:
    name: mysql-network
    driver: overlay
    external: true

services:
  rest-server:
    container_name: rest-server
    restart: always
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - SERVER_PORT=3000
      - DB_SERVER_IP=mysql1
      - DB_SERVER_PORT=3306
    command: npm start
    networks:
      - mysql-network
